name: Build & Publish

on:
  push:
    branches: [v2]

env:
  NEXT_PUBLIC_STRAPI_API_URL: ${{secrets.NEXT_PUBLIC_STRAPI_API_URL}}
  NEXT_PUBLIC_MATOMO_URL: ${{secrets.NEXT_PUBLIC_MATOMO_URL}}
  NEXT_PUBLIC_MATOMO_SITE_ID: ${{secrets.NEXT_PUBLIC_MATOMO_SITE_ID}}
  NEXT_PUBLIC_MATOMO_API_KEY: ${{secrets.NEXT_PUBLIC_MATOMO_API_KEY}}
  NEXT_PUBLIC_WEBMENTION_KEY: ${{secrets.NEXT_PUBLIC_WEBMENTION_KEY}}
  NEXT_PUBLIC_IMGPROXY_URL: ${{secrets.NEXT_PUBLIC_IMGPROXY_URL}}
  NEXT_PUBLIC_IMGPROXY_KEY: ${{secrets.NEXT_PUBLIC_IMGPROXY_KEY}}
  NEXT_PUBLIC_IMGPROXY_SALT: ${{secrets.NEXT_PUBLIC_IMGPROXY_SALT}}
  DASHBOARD_GITHUB_PAK: ${{secrets.GITHUB_PAK}}
  OPENWEATHER_API_KEY: ${{secrets.OPENWEATHER_API_KEY}}

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |         
            ${{ secrets.DOCKER_HUB_USERNAME}}/personal-website:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/personal-website:latest
          build-args: |
            NEXT_PUBLIC_STRAPI_API_URL=${{ env.NEXT_PUBLIC_STRAPI_API_URL }}
            NEXT_PUBLIC_MATOMO_URL=${{ env.NEXT_PUBLIC_MATOMO_URL }}
            NEXT_PUBLIC_MATOMO_SITE_ID=${{ env.NEXT_PUBLIC_MATOMO_SITE_ID }}
            NEXT_PUBLIC_MATOMO_API_KEY=${{ env.NEXT_PUBLIC_MATOMO_API_KEY }}
            NEXT_PUBLIC_WEBMENTION_KEY=${{ env.NEXT_PUBLIC_WEBMENTION_KEY }}
            NEXT_PUBLIC_IMGPROXY_URL=${{ env.NEXT_PUBLIC_IMGPROXY_URL }}
            DASHBOARD_GITHUB_PAK=${{ env.DASHBOARD_GITHUB_PAK }}
            OPENWEATHER_API_KEY=${{ env.OPENWEATHER_API_KEY }}
            NEXT_PUBLIC_IMGPROXY_KEY=${{ env.NEXT_PUBLIC_IMGPROXY_KEY }}
            NEXT_PUBLIC_IMGPROXY_SALT=${{ env.NEXT_PUBLIC_IMGPROXY_SALT }}