name: Trigger auto deployment for personal-website

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ v2 ]
    paths:
    - '**'
    - '.github/workflows/personal-website-AutoDeployTrigger-e999d100-1bba-46e9-8d19-7df94d11e9f4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PERSONALWEBSITE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PERSONALWEBSITE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PERSONALWEBSITE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: registry.hub.docker.com
          registryUsername: ${{ secrets.PERSONALWEBSITE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PERSONALWEBSITE_REGISTRY_PASSWORD }}
          containerAppName: personal-website
          resourceGroup: RG-MXDCODES
          imageToBuild: registry.hub.docker.com/personal-website:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


